name: Choose Machine

on:
  push:
    branches:
      - main
      - release-icu4c-ubuntu.yml
  workflow_dispatch:
    inputs:
      machine:
        type: choice
        description: Choose Machine
        options: 
        - ubuntu-24.04-arm
        - self-hosted, ubuntu-22.04, ARM64
      environment:
        type: environment

jobs:
  greet:
    runs-on: "${{ github.event.inputs.machine }}"

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.machine }}"
